# Generated by Django 2.2.1 on 2019-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
